import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { buildLocaleAlternates, BASE_URL } from "../../../../lib/alternates";
import { isLocale } from "../../../../lib/blog";
import type { Locale } from "../../../../lib/i18n";
import { JsonLd } from "../../../components/seo/JsonLd";

const COPY:Record<Locale,{title:string;description:string;body:string;scope:string}>={en:{title:"Sweezy Team",description:"Editorial team behind Sweezy guides for newcomers to Switzerland.",body:"Sweezy Team researches and structures practical guidance for newcomers in Switzerland. Work combines official federal, cantonal and municipal sources with task-focused editing in English, Ukrainian and German.",scope:"Team does not claim legal, tax or medical credentials. Where qualified external review exists, named reviewer appears on specific article."},uk:{title:"Команда Sweezy",description:"Редакційна команда гідів Sweezy для новоприбулих у Швейцарії.",body:"Команда Sweezy досліджує й структурує практичні матеріали для новоприбулих у Швейцарії. Робота поєднує офіційні федеральні, кантональні й муніципальні джерела з орієнтованою на завдання редактурою українською, англійською та німецькою.",scope:"Команда не заявляє юридичної, податкової чи медичної кваліфікації. Якщо матеріал перевірив зовнішній фахівець, його ім'я вказане на конкретній статті."},de:{title:"Sweezy Team",description:"Redaktionsteam hinter Sweezy-Guides für Neuzuzüger in der Schweiz.",body:"Sweezy Team recherchiert und strukturiert praktische Orientierung für Neuzuzüger. Offizielle Quellen von Bund, Kantonen und Gemeinden werden mit aufgabenorientierter Redaktion auf Deutsch, Ukrainisch und Englisch verbunden.",scope:"Das Team beansprucht keine Rechts-, Steuer- oder Medizinqualifikation. Externe Fachprüfung wird beim konkret geprüften Artikel namentlich ausgewiesen."}};
export function generateStaticParams(){return ["en","uk","de"].map(locale=>({locale}));}
export function generateMetadata({params}:{params:{locale:string}}):Metadata{if(!isLocale(params.locale))return{};const c=COPY[params.locale];return{title:`${c.title} | Sweezy`,description:c.description,alternates:buildLocaleAlternates(params.locale,"/authors/sweezy-team")};}
export default function Page({params}:{params:{locale:string}}){if(!isLocale(params.locale))notFound();const c=COPY[params.locale];const url=`${BASE_URL}/${params.locale}/authors/sweezy-team`;return <main lang={params.locale} className="min-h-screen bg-dark-900 text-white"><JsonLd data={{"@context":"https://schema.org","@type":"Organization",name:"Sweezy Team",url,parentOrganization:{"@type":"Organization",name:"Sweezy",url:BASE_URL},knowsLanguage:["uk","en","de"]}}/><article className="mx-auto max-w-4xl px-6 py-20"><p className="text-xs font-semibold tracking-[.22em] text-accent-green">AUTHOR · SWITZERLAND</p><h1 className="mt-6 text-6xl font-bold tracking-tight sm:text-8xl">{c.title}</h1><p className="mt-8 max-w-3xl text-xl leading-9 text-white/65">{c.body}</p><div className="mt-12 rounded-2xl border border-white/10 bg-white/[.03] p-7"><h2 className="text-2xl font-semibold">Scope and disclosure</h2><p className="mt-4 leading-8 text-white/55">{c.scope}</p></div><div className="mt-10 flex flex-wrap gap-3"><Link className="rounded-full bg-accent-green px-5 py-3 font-bold text-black" href={`/${params.locale}/editorial`}>Editorial standards →</Link><Link className="rounded-full border border-white/15 px-5 py-3 font-bold" href={`/${params.locale}/blog`}>Guides →</Link></div></article></main>}
