import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { buildLocaleAlternates, BASE_URL } from "../../../lib/alternates";
import { isLocale } from "../../../lib/blog";
import type { Locale } from "../../../lib/i18n";
import { JsonLd } from "../../components/seo/JsonLd";

const COPY:Record<Locale,{title:string;description:string;intro:string;principles:[string,string][];updates:string;corrections:string;ownership:string}>={
  en:{title:"Sweezy editorial standards",description:"How Sweezy researches, sources, reviews, corrects and updates guidance about life in Switzerland.",intro:"Sweezy turns fragmented official information into practical orientation. We prioritize primary Swiss sources, state jurisdiction and applicability, and never present general guidance as personal legal, tax, financial or medical advice.",principles:[["Primary sources","Federal, cantonal and municipal authorities come before summaries, forums or commercial pages."],["Answer first","Important guides begin with a direct answer, then explain exceptions, evidence and next actions."],["Visible scope","Nationality, permit, canton, municipality and effective date are stated when they change the answer."],["No invented authority","Reviewer names, ratings, user counts and credentials appear only when independently verifiable."]],updates:"Time-sensitive guidance is reviewed after meaningful authority changes. A reviewed date changes only when content was checked; a modified date changes only after substantive edits.",corrections:"Send page URL, disputed statement and supporting source to support@sweezy.world. Material corrections are documented in the page change log.",ownership:"Sweezy Team owns research and production. Qualified external review is disclosed only after a named specialist has reviewed the specific material."},
  uk:{title:"Редакційні стандарти Sweezy",description:"Як Sweezy досліджує, перевіряє, виправляє й оновлює матеріали про життя у Швейцарії.",intro:"Sweezy перетворює розрізнену офіційну інформацію на практичні орієнтири. Ми спираємося на першоджерела Швейцарії, вказуємо юрисдикцію й межі застосування та не видаємо загальну інформацію за персональну юридичну, податкову, фінансову чи медичну консультацію.",principles:[["Першоджерела","Федеральні, кантональні та муніципальні органи мають пріоритет над оглядами, форумами й комерційними сторінками."],["Відповідь спочатку","Важливі гіди починаються з прямої відповіді, далі пояснюють винятки, докази та наступні дії."],["Видимі межі","Громадянство, дозвіл, кантон, громада й дата дії вказуються, коли вони змінюють відповідь."],["Без вигаданого авторитету","Імена рецензентів, рейтинги, кількість користувачів і кваліфікації з'являються лише після незалежної перевірки."]],updates:"Чутливі до часу матеріали перевіряємо після суттєвих змін у джерелах. Дата перевірки змінюється після фактичної перевірки, дата оновлення — після змістовної редакції.",corrections:"Надішліть URL, спірне твердження та підтверджувальне джерело на support@sweezy.world. Суттєві виправлення фіксуємо в історії змін сторінки.",ownership:"Sweezy Team відповідає за дослідження й підготовку. Зовнішню експертну перевірку зазначаємо лише після перевірки конкретного матеріалу названим фахівцем."},
  de:{title:"Redaktionelle Standards von Sweezy",description:"Wie Sweezy Informationen zum Leben in der Schweiz recherchiert, belegt, prüft und aktualisiert.",intro:"Sweezy übersetzt verteilte Behördeninformationen in praktische Orientierung. Primärquellen, Zuständigkeit und Geltungsbereich bleiben sichtbar. Allgemeine Informationen ersetzen keine persönliche Rechts-, Steuer-, Finanz- oder Medizinberatung.",principles:[["Primärquellen","Bundes-, Kantons- und Gemeindebehörden haben Vorrang vor Zusammenfassungen, Foren und kommerziellen Seiten."],["Antwort zuerst","Wichtige Guides beginnen mit einer direkten Antwort und erklären danach Ausnahmen, Belege und nächste Schritte."],["Sichtbarer Geltungsbereich","Nationalität, Bewilligung, Kanton, Gemeinde und Stichtag werden genannt, wenn sie die Antwort verändern."],["Keine erfundene Autorität","Reviewer, Bewertungen, Nutzerzahlen und Qualifikationen erscheinen nur, wenn sie nachweisbar sind."]],updates:"Zeitkritische Inhalte werden nach wesentlichen Behördenänderungen geprüft. Prüf- und Änderungsdaten werden nur nach echter Kontrolle oder substanzieller Bearbeitung geändert.",corrections:"Seiten-URL, strittige Aussage und Beleg an support@sweezy.world senden. Wesentliche Korrekturen werden im Änderungsverlauf dokumentiert.",ownership:"Sweezy Team verantwortet Recherche und Produktion. Externe Fachprüfung wird nur nach Prüfung des konkreten Inhalts durch eine namentlich genannte Person ausgewiesen."}}

export function generateStaticParams(){return ["en","uk","de"].map(locale=>({locale}));}
export function generateMetadata({params}:{params:{locale:string}}):Metadata{if(!isLocale(params.locale))return{};const c=COPY[params.locale];return{title:c.title,description:c.description,alternates:buildLocaleAlternates(params.locale,"/editorial")};}
export default function Page({params}:{params:{locale:string}}){if(!isLocale(params.locale))notFound();const c=COPY[params.locale];const url=`${BASE_URL}/${params.locale}/editorial`;const schema={"@context":"https://schema.org","@type":"WebPage",name:c.title,description:c.description,url,inLanguage:params.locale,about:{"@type":"Organization",name:"Sweezy",url:BASE_URL}};return <main lang={params.locale} className="min-h-screen bg-dark-900 text-white"><JsonLd data={schema}/><article className="mx-auto max-w-5xl px-6 py-16 sm:py-24"><Link href={`/${params.locale}/about`} className="text-sm text-white/45">← Sweezy</Link><header className="mt-10 border-b border-white/10 pb-12"><p className="text-xs font-semibold tracking-[.22em] text-accent-green">EDITORIAL · TRUST · SOURCES</p><h1 className="mt-5 max-w-4xl text-5xl font-bold tracking-tight sm:text-7xl">{c.title}</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/65">{c.intro}</p></header><section className="grid gap-3 py-12 sm:grid-cols-2">{c.principles.map(([title,body],i)=><article key={title} className="rounded-2xl border border-white/10 bg-white/[.03] p-7"><span className="text-xs font-bold text-accent-green">0{i+1}</span><h2 className="mt-8 text-2xl font-semibold">{title}</h2><p className="mt-3 leading-7 text-white/55">{body}</p></article>)}</section><section className="grid gap-5 border-t border-white/10 py-12 md:grid-cols-3">{[["Updates",c.updates],["Corrections",c.corrections],["Ownership",c.ownership]].map(([title,body])=><div key={title}><h2 className="text-xl font-semibold">{title}</h2><p className="mt-3 leading-7 text-white/55">{body}</p></div>)}</section></article></main>}
