import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { buildLocaleAlternates, BASE_URL } from "../../../lib/alternates";
import { isLocale } from "../../../lib/blog";
import type { Locale } from "../../../lib/i18n";
import { jobs } from "../../../data/jobs";
import styles from "./jobs.module.css";

const COPY: Record<Locale, any> = {
  en:{title:"Jobs in Switzerland, made easier to find",accent:"made easier",description:"Verified opportunities for international talent, newcomers and Ukrainians in Switzerland. Employers can submit a vacancy for review.",eyebrow:"SWEEZY JOBS · SWITZERLAND",post:"Post a vacancy",guide:"Job search guide",route:["Employer submits","Sweezy reviews","Candidate applies"],section:"Work that fits real life",sectionBody:"Clear location, workload, language and permit information before a candidate applies.",categories:[["Local roles","Hospitality, retail and services"],["Office & tech","Operations, product and support"],["Skilled work","Construction, logistics and care"],["Flexible","Part-time, hybrid and remote"]],openTitle:"Vacancy board opening",openBody:"First employer submissions are being reviewed. No scraped, expired or anonymous listings: only vacancies checked by Sweezy.",empty:"No verified vacancies published yet.",seo:"Jobs in Switzerland for expats and Ukrainians. Browse verified vacancies or post a job for review on Sweezy."},
  uk:{title:"Робота у Швейцарії, яку легше знайти",accent:"легше знайти",description:"Перевірені вакансії для українців, новоприбулих та міжнародних фахівців у Швейцарії. Роботодавці можуть подати вакансію на модерацію.",eyebrow:"SWEEZY JOBS · ШВЕЙЦАРІЯ",post:"Розмістити вакансію",guide:"Гід із пошуку роботи",route:["Роботодавець подає","Sweezy перевіряє","Кандидат відгукується"],section:"Робота для реального життя",sectionBody:"Місто, зайнятість, мови й вимоги до дозволу видно до відгуку.",categories:[["Локальна робота","Готелі, магазини та сервіси"],["Офіс і tech","Операції, product та support"],["Кваліфікована праця","Будівництво, логістика й догляд"],["Гнучкий формат","Part-time, hybrid та remote"]],openTitle:"Дошка вакансій відкривається",openBody:"Перші заявки роботодавців проходять перевірку. Без парсингу, прострочених чи анонімних оголошень — лише вакансії після модерації Sweezy.",empty:"Перевірених вакансій ще немає.",seo:"Вакансії у Швейцарії для українців і новоприбулих. Знайдіть роботу або розмістіть вакансію на Sweezy."},
  de:{title:"Jobs in der Schweiz, leichter zu finden",accent:"leichter",description:"Geprüfte Stellen für internationale Talente, Neuankömmlinge und Ukrainer in der Schweiz. Arbeitgeber können Stellen zur Prüfung einreichen.",eyebrow:"SWEEZY JOBS · SCHWEIZ",post:"Stelle veröffentlichen",guide:"Ratgeber zur Jobsuche",route:["Arbeitgeber reicht ein","Sweezy prüft","Talent bewirbt sich"],section:"Arbeit, die zum Leben passt",sectionBody:"Ort, Pensum, Sprache und Bewilligungsanforderungen sind vor der Bewerbung klar.",categories:[["Lokale Jobs","Gastronomie, Handel und Services"],["Office & Tech","Operations, Product und Support"],["Facharbeit","Bau, Logistik und Pflege"],["Flexibel","Teilzeit, hybrid und remote"]],openTitle:"Jobbörse startet",openBody:"Erste Arbeitgeber-Einreichungen werden geprüft. Keine gescrapten, abgelaufenen oder anonymen Anzeigen — nur von Sweezy geprüfte Stellen.",empty:"Noch keine geprüften Stellen veröffentlicht.",seo:"Jobs in der Schweiz für internationale Talente und Ukrainer. Stellen finden oder Job bei Sweezy einreichen."}
};
const guideHref:Record<Locale,string>={en:"/en/blog/how-to-find-job-switzerland-foreigner",uk:"/uk/blog/poshuk-roboty-u-shveytcariyi",de:"/de/guides"};
export function generateStaticParams(){return [{locale:"en"},{locale:"uk"},{locale:"de"}]}
export async function generateMetadata({params}:{params:{locale:string}}):Promise<Metadata>{if(!isLocale(params.locale))return{};const c=COPY[params.locale];return{title:c.title,description:c.seo,keywords:params.locale==="uk"?["вакансії у Швейцарії","робота у Швейцарії для українців","знайти роботу у Швейцарії","вакансії Швейцарія"]:["jobs in Switzerland","jobs Switzerland expats","Swiss jobs","post a job Switzerland"],alternates:buildLocaleAlternates(params.locale,"/jobs"),openGraph:{title:c.title,description:c.seo,url:`${BASE_URL}/${params.locale}/jobs`,type:"website"}}}
export default function JobsPage({params}:{params:{locale:string}}){if(!isLocale(params.locale))notFound();const locale=params.locale;const c=COPY[locale];const schema={"@context":"https://schema.org","@type":"CollectionPage",name:c.title,description:c.seo,url:`${BASE_URL}/${locale}/jobs`,mainEntity:{"@type":"ItemList",numberOfItems:jobs.length,itemListElement:[]}};return <main lang={locale} className={styles.page}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,"\\u003c")}}/><div className={styles.shell}><section className={styles.hero}><div className={styles.heroCopy}><div><p className={styles.eyebrow}>{c.eyebrow}</p><h1>{c.title.replace(c.accent,"")}<em>{c.accent}</em></h1><p>{c.description}</p><div className={styles.heroActions}><Link className={styles.primary} href={`/${locale}/jobs/post`}>{c.post}<span aria-hidden>→</span></Link><Link className={styles.secondary} href={guideHref[locale]}>{c.guide}<span aria-hidden>↗</span></Link></div></div><p className={styles.eyebrow}>VERIFIED · LOCAL · HUMAN REVIEW</p></div><div className={styles.route} aria-label={c.route.join(", ")}><span className={styles.routeNode}>01</span><span className={styles.routeNode}>02</span><span className={styles.routeNode}>03</span><div className={styles.routeLabel}><span className={styles.eyebrow}>START</span><strong>{c.route[0]}</strong></div><div className={styles.routeLabel}><span className={styles.eyebrow}>MATCH</span><strong>{c.route[2]}</strong></div></div></section><header className={styles.sectionHead}><div><p className={styles.eyebrow}>SWISS WORK MAP</p><h2>{c.section}</h2></div><p>{c.sectionBody}</p></header><div className={styles.categories}>{c.categories.map((x:string[],i:number)=><article className={styles.category} key={x[0]}><span className={styles.eyebrow}>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div><section className={styles.empty}><div><p className={styles.eyebrow}>{c.empty}</p><h3>{c.openTitle}</h3><p>{c.openBody}</p></div><Link className={styles.primary} href={`/${locale}/jobs/post`}>{c.post}<span aria-hidden>→</span></Link></section></div></main>}

