"use client";

import { FormEvent, useState } from "react";
import type { Locale } from "../../../../lib/i18n";
import styles from "../jobs.module.css";

const COPY: Record<Locale, any> = {
  en:{groups:[["Company","Who is hiring and who can Sweezy contact?"],["Vacancy","Give candidates enough detail to decide."],["Application","Where should a qualified person apply?"]],company:"Company name",website:"Company website",name:"Contact person",email:"Work email",title:"Job title",city:"City or municipality",canton:"Canton",type:"Employment type",types:[["full-time","Full-time"],["part-time","Part-time"],["contract","Contract"],["temporary","Temporary"]],workplace:"Workplace",places:[["onsite","On-site"],["hybrid","Hybrid"],["remote","Remote"]],languages:"Required languages",salary:"Salary or range (optional)",description:"Role description",descriptionHint:"Responsibilities, schedule, team and what makes this role useful.",requirements:"Requirements",application:"Application URL or email",deadline:"Application deadline (optional)",consent:"I confirm this vacancy is real, current and may be reviewed by Sweezy before publication.",submit:"Send vacancy for review",sending:"Sending…",success:"Vacancy received. Sweezy will review it before publication.",error:"Vacancy was not delivered. Check fields or send it by email.",fallback:"Send prepared email",optional:"Optional"},
  uk:{groups:[["Компанія","Хто наймає та з ким Sweezy може зв’язатися?"],["Вакансія","Дайте кандидату достатньо інформації для рішення."],["Відгук","Куди має звернутися відповідний кандидат?"]],company:"Назва компанії",website:"Сайт компанії",name:"Контактна особа",email:"Робочий email",title:"Назва вакансії",city:"Місто або громада",canton:"Кантон",type:"Тип зайнятості",types:[["full-time","Повна"],["part-time","Неповна"],["contract","Контракт"],["temporary","Тимчасова"]],workplace:"Формат роботи",places:[["onsite","На місці"],["hybrid","Гібрид"],["remote","Віддалено"]],languages:"Необхідні мови",salary:"Зарплата або діапазон (необов’язково)",description:"Опис ролі",descriptionHint:"Обов’язки, графік, команда та умови роботи.",requirements:"Вимоги",application:"Посилання або email для відгуку",deadline:"Дедлайн відгуку (необов’язково)",consent:"Підтверджую, що вакансія реальна й актуальна та може пройти перевірку Sweezy перед публікацією.",submit:"Надіслати на перевірку",sending:"Надсилаємо…",success:"Вакансію отримано. Sweezy перевірить її перед публікацією.",error:"Вакансію не доставлено. Перевірте поля або надішліть її email.",fallback:"Надіслати підготовлений email",optional:"Необов’язково"},
  de:{groups:[["Unternehmen","Wer stellt ein und wen darf Sweezy kontaktieren?"],["Stelle","Genug Details für eine gute Entscheidung."],["Bewerbung","Wo soll sich eine passende Person bewerben?"]],company:"Unternehmensname",website:"Website",name:"Kontaktperson",email:"Geschäftliche E-Mail",title:"Stellentitel",city:"Ort oder Gemeinde",canton:"Kanton",type:"Anstellungsart",types:[["full-time","Vollzeit"],["part-time","Teilzeit"],["contract","Vertrag"],["temporary","Befristet"]],workplace:"Arbeitsort",places:[["onsite","Vor Ort"],["hybrid","Hybrid"],["remote","Remote"]],languages:"Erforderliche Sprachen",salary:"Lohn oder Spanne (optional)",description:"Stellenbeschreibung",descriptionHint:"Aufgaben, Pensum, Team und Arbeitsbedingungen.",requirements:"Anforderungen",application:"Bewerbungslink oder E-Mail",deadline:"Bewerbungsfrist (optional)",consent:"Ich bestätige, dass diese Stelle real und aktuell ist und vor Veröffentlichung von Sweezy geprüft werden darf.",submit:"Stelle zur Prüfung senden",sending:"Wird gesendet…",success:"Stelle erhalten. Sweezy prüft sie vor Veröffentlichung.",error:"Stelle wurde nicht zugestellt. Felder prüfen oder per E-Mail senden.",fallback:"Vorbereitete E-Mail senden",optional:"Optional"}
};

export function EmployerJobForm({locale}:{locale:Locale}){
  const c=COPY[locale]; const [state,setState]=useState<"idle"|"sending"|"success"|"error">("idle"); const [fallback,setFallback]=useState("mailto:jobs@sweezy.world");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setState("sending");const form=event.currentTarget;const values=Object.fromEntries(new FormData(form).entries());const subject=`Sweezy job: ${values.title||"Vacancy"} — ${values.company||"Employer"}`;const body=Object.entries(values).filter(([key])=>key!=="consent"&&key!=="company_fax").map(([key,value])=>`${key}: ${value}`).join("\n\n");setFallback(`mailto:jobs@sweezy.world?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`);try{const response=await fetch("/api/jobs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...values,locale})});if(!response.ok)throw new Error("delivery-failed");setState("success");form.reset()}catch{setState("error")}}
  const field=(name:string,label:string,type="text",required=true,extra:any={})=><div className={styles.field}><label htmlFor={name}>{label}{!required?` · ${c.optional}`:""}</label><input id={name} name={name} type={type} required={required} {...extra}/></div>;
  return <form className={styles.form} onSubmit={submit} noValidate={false}>{state!=="idle"&&<div role="status" className={`${styles.status} ${state==="success"?styles.success:state==="error"?styles.error:""}`}>{state==="sending"?c.sending:state==="success"?c.success:<>{c.error}<br/><a className={styles.fallback} href={fallback}>{c.fallback} →</a></>}</div>}<div className={styles.honeypot} aria-hidden><label htmlFor="company_fax">Company fax</label><input id="company_fax" name="company_fax" tabIndex={-1} autoComplete="off"/></div><section className={styles.group}><h2>{c.groups[0][0]}</h2><p className={styles.groupIntro}>{c.groups[0][1]}</p>{field("company",c.company)}{field("website",c.website,"url",false,{placeholder:"https://"})}{field("contactName",c.name)}{field("email",c.email,"email")}</section><section className={styles.group}><h2>{c.groups[1][0]}</h2><p className={styles.groupIntro}>{c.groups[1][1]}</p>{field("title",c.title)}{field("city",c.city)}{field("canton",c.canton)}<fieldset className={styles.fieldset}><legend>{c.type}</legend><div className={styles.radioGrid}>{c.types.map(([v,l]:string[],i:number)=><label className={styles.radio} key={v}><input type="radio" name="employmentType" value={v} defaultChecked={i===0}/><span>{l}</span></label>)}</div></fieldset><fieldset className={styles.fieldset}><legend>{c.workplace}</legend><div className={styles.radioGrid}>{c.places.map(([v,l]:string[],i:number)=><label className={styles.radio} key={v}><input type="radio" name="workplace" value={v} defaultChecked={i===0}/><span>{l}</span></label>)}</div></fieldset>{field("languages",c.languages)}{field("salary",c.salary,"text",false)}<div className={styles.field}><label htmlFor="description">{c.description}</label><span className={styles.hint}>{c.descriptionHint}</span><textarea id="description" name="description" minLength={120} maxLength={4000} required/></div><div className={styles.field}><label htmlFor="requirements">{c.requirements}</label><textarea id="requirements" name="requirements" minLength={40} maxLength={2500} required/></div></section><section className={styles.group}><h2>{c.groups[2][0]}</h2><p className={styles.groupIntro}>{c.groups[2][1]}</p>{field("application",c.application)}{field("deadline",c.deadline,"date",false)}<label className={styles.check}><input type="checkbox" name="consent" value="confirmed" required/><span>{c.consent}</span></label></section><button className={styles.submit} type="submit" disabled={state==="sending"}>{state==="sending"?c.sending:c.submit}<span aria-hidden>→</span></button></form>
}
